# Generated by Django 4.2 on 2023-05-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='User',
        ),
    ]
