# Generated by Django 4.2 on 2023-05-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_newuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='new_user',
        ),
    ]
